name: anew_home_task
description: A new Flutter project.



version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/newYorkTimes.jpg
  fonts:
    - family: Chomsky
      fonts:
        - asset: assets/fonts/Chomsky.otf
    - family: Lora-VariableFont
      fonts:
        - asset: assets/fonts/Lora-VariableFont_wght.ttf
    - family: PlayfairDisplay
    - fonts:
        - asset: assets/fonts/PlayfairDisplay-italic-VariableFont_wght.ttf


